% x=gendata(10000,{"powerlaw",2.5});
% x=pldist(1000);
% asdf2=cbmodel(0.26);
%% Shape Collapse Analysis (NCC toolbox)


% Retrieve all the files in a directory
% names = dir('/Users/fhabibollahi/Desktop/MelbournePhD/CorticalLabs/Results/Results on Motor and Sensory Regions/Motor/Active/*.txt');


Spikes = zeros(1,size(names,1));
for i = 1:size(names,1)
    filename = [ names(i).folder,'/', names(i).name];
%   filename = names;
    delimiterIn = ' ';
    data = importdata(filename,delimiterIn);
    data = full(spones(data));
    raster = {};
    for ii =1: size(data,1)
      raster{ii} = find(data(ii,:));
    end

    raster = reshape(raster,[size(raster,2) size(raster,1)]);


    asdf2.binsize = 1;
    asdf2.nbins = length(data);
    asdf2.nchannels = size(data,1);
    asdf2.expsys = 'CBModel';
    asdf2.datatype = 'Spikes';
    asdf2.dataID= 'ModelX';
    asdf2.raster = raster;

    %  load sample_data.mat % Load the data: ?an example neural avalanche data set generated by the 
    % %cortical branching model

    Av=avprops(asdf2);%Findtheavalanches
    
    %%%% *********** important*********** %%%%%%%
    
   
    try  
        avgProfiles=avgshapes(Av.shape,Av.duration,'cutoffs',4,20); 
        

        % SNZsc is the shape collapse (beta in the DCC analysis)
        [SNZsc,secondDrv,range,errors]= avshapecollapse(avgProfiles,'plot');
        Spikes(1,i) = SNZsc;
    
%     tempTable.filename = names(i).name; 
%     tempTable.SNZsc = SNZsc; 
    
    
%         ylim([1 3.5]);
    % sigmaSNZsc is the shape collapse extimation error
        sigmaSNZsc=avshapecollapsestd(avgProfiles);
        disp('the SNZsc must be very close to fitted \beta from the DCC analysis');
    catch
        fprintf('loop number %d failed\n',i)
    end
%      close all
end

%% Save the results in .mat files:
Actives = Spikes';
%Rests = Spikes';

%  close all
